language: android
sudo: required
jdk: oraclejdk8
dist: trusty
before_cache:
  -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  -rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  -$HOME/.gradle/caches/
  -$HOME/.gradle/wrapper/
  -$HOME/.android/build-cache
env:
  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
android:
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - chmod +x gradlew
  - ./gradlew dependencies || true
before_script:
  # Prepare pre-accepted licenses to not be promted at installation
  - mkdir -p "$ANDROID_HOME/licenses"
  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
script:
  - gradlew clean build check --stacktrace